### 0. Generate auth token
### Запрос на получение токена CSRF для аутентификации
# curl -u admin:admin "http://192.168.0.25:8111/authenticationTest.html2
GET http://192.168.0.25:8111/authenticationTest.html?csrf
Authorization: Basic admin admin


### 1. Create project
### Запрос на создание проекта
POST http://192.168.0.25:8111/app/rest/projects
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: 8947fd6a-2fc6-405f-a6a8-25e0c759d934

{
  "parentProject": {
    "locator": "_Root"
  },
  "name": "name33",
  "id": "id33",
  "copyAllAssociatedSettings": true
}

### 2. Create build configuration
### Запрос на создание конфигурации сборки
POST http://192.168.0.25:8111/app/rest/buildTypes
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: 8947fd6a-2fc6-405f-a6a8-25e0c759d934

{
  "id": "id_build33",
  "name": "Print hello world",
  "project": {
    "id": "id33"
  },
  "steps": {
    "step": [
      {
        "name": "Print hello world",
        "type": "simpleRunner",
        "properties": {
          "property": [
            {
              "name": "script.content",
              "value": "echo 'Hello World!'"
            },
            {
              "name": "teamcity.step.mode",
              "value": "default"
            },
            {
              "name": "use.custom.script",
              "value": "true"
            }
          ]
        }
      }
    ]
  }
}

### 3. Run build
### Запрос на запуск сборки
POST http://192.168.0.25:8111/app/rest/buildQueue
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: 8947fd6a-2fc6-405f-a6a8-25e0c759d934

{
  "buildType": {
    "id": "id_build33"
  }
}

### 4. Check build status
### Запрос на получение статуса сборки
GET http://192.168.0.25:8111/app/rest/builds/id:202
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: b8dffa16-d788-4b48-ba47-f62c87712067


### 5. Turn on permissions
PUT http://192.168.0.25:8111/app/rest/server/authSettings
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: b8dffa16-d788-4b48-ba47-f62c87712067

{
  "allowGuest": false,
  "guestUsername": "guest",
  "collapseLoginForm": false,
  "perProjectPermissions": true,
  "emailVerification": false,
  "modules": {
    "module": [
      {
        "name": "Default",
        "properties": {
          "property": [
            {
              "name": "usersCanResetOwnPasswords",
              "value": "true"
            },
            {
              "name": "usersCanChangeOwnPasswords",
              "value": "true"
            },
            {
              "name": "freeRegistrationAllowed",
              "value": "false"
            }
          ],
          "count": 3
        }
      },
      {
        "name": "Token-Auth",
        "properties": {
          "property": [],
          "count": 0
        }
      },
      {
        "name": "HTTP-Basic",
        "properties": {
          "property": [],
          "count": 0
        }
      }
    ]
  }
}

### 6. Verify permissions
#X-TC-CSRF-Token: 74a7cb06-c2b1-4bab-8582-34a95dd52ab0
GET http://192.168.0.25:8111/app/rest/server/authSettings
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: b8dffa16-d788-4b48-ba47-f62c87712067

### 7. Find projects
GET http://192.168.0.25:8111/app/rest/projects
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: b8dffa16-d788-4b48-ba47-f62c87712067

### 8. Find project
GET http://192.168.0.25:8111/app/rest/projects/id%3Atest_nxyRnAuWmp
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: 8947fd6a-2fc6-405f-a6a8-25e0c759d934

### 9. Delete project
DELETE  http://192.168.0.25:8111/app/rest/projects/id%3ATestJApUNYeQxh
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: 8947fd6a-2fc6-405f-a6a8-25e0c759d934

### 10. Find builds
GET http://192.168.0.25:8111/app/rest/buildTypes
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: b8dffa16-d788-4b48-ba47-f62c87712067

### 11. Find build
GET http://192.168.0.25:8111/app/rest/buildTypes/id%3ATestiXBIbUXnsw_TestDXJAJTZYzR
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: b8dffa16-d788-4b48-ba47-f62c87712067

### 12. Put agent
PUT http://192.168.0.25:8111/app/rest/agents/ip_172.17.0.1/authorized
Content-Type: text/plain
Accept: text/plain
X-TC-CSRF-Token: b8dffa16-d788-4b48-ba47-f62c87712067

true

### 13. Get agents /app/rest/agents
GET http://%3A1630286690547818307@192.168.0.25:8111/app/rest/agents
Content-Type: application/json
Accept: application/json